# Generated by Django 2.2.8 on 2020-10-10 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='photos',
            name='Photo',
        ),
        migrations.AddField(
            model_name='photos',
            name='photo_category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='gallery.Category'),
        ),
        migrations.AddField(
            model_name='photos',
            name='photo_location',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='gallery.Location'),
        ),
    ]
