# Generated by Django 2.2.8 on 2020-10-10 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_auto_20201010_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='photos',
            name='Photo',
            field=models.ImageField(default='image.jpg', upload_to='images/'),
        ),
    ]
