# Generated by Django 2.2.8 on 2020-10-11 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_photos_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photos',
            name='photo_location',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='gallery.Location'),
        ),
    ]
