# Generated by Django 2.2.8 on 2020-10-11 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_auto_20201011_1254'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photos',
            old_name='Photo',
            new_name='photo',
        ),
    ]
