# Generated by Django 2.2.8 on 2020-10-12 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0006_auto_20201012_0440'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photos',
            old_name='photo_category',
            new_name='category',
        ),
    ]
