# Generated by Django 2.2.8 on 2020-10-12 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0007_auto_20201012_0457'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photos',
            old_name='category',
            new_name='photo_category',
        ),
    ]
